// Custom logo images supplied directly by the curator, served from /public/logos.
// Takes priority over the simple-icons match in companyLogos.ts.
export const companyLogoImages: Record<string, string> = {
  Adobe: "/logos/adobe.png",
  Agima: "/logos/agima.png",
  Airbnb: "/logos/airbnb.png",
  "Alfa Bank": "/logos/alfa-bank.png",
  Apple: "/logos/apple.png",
  "Art. Lebedev Studio": "/logos/art-lebedev.jpeg",
  Aviasales: "/logos/aviasales.png",
  Avito: "/logos/avito.png",
  Badoo: "/logos/badoo.jpeg",
  Beeline: "/logos/beeline.png",
  Citimobil: "/logos/citimobil.png",
  CreativePeople: "/logos/creativepeople.png",
  Delimobil: "/logos/delimobil.jpeg",
  Dodo: "/logos/dodo.jpeg",
  Drinkit: "/logos/drinkit.png",
  Facebook: "/logos/facebook.png",
  Flo: "/logos/flo.png",
  Flowwow: "/logos/flowwow.png",
  Framer: "/logos/framer.png",
  Gazprom: "/logos/gazprom.png",
  Google: "/logos/google.png",
  Higgsfield: "/logos/higgsfield.png",
  Holographik: "/logos/holographik.jpeg",
  "Home Credit": "/logos/home-credit.png",
  IBM: "/logos/ibm.png",
  Instagram: "/logos/instagram.jpeg",
  Instories: "/logos/instories.jpeg",
  Mail: "/logos/mail.jpeg",
  Megafon: "/logos/megafon.png",
  Meta: "/logos/meta.jpeg",
  Microsoft: "/logos/microsoft.jpeg",
  Mish: "/logos/mish.jpeg",
  MTS: "/logos/mts.png",
  Mymind: "/logos/mymind.png",
};
